AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Style/StringLiterals:
  Enabled: false  # permite usar aspas simples ou duplas

Layout/TrailingWhitespace:
  Enabled: false  # não exige apagar espaços no fim da linha

Layout/TrailingEmptyLines:
  Enabled: false  # não exige linha em branco no final do arquivo

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false  # não exige espaçamento exato em arrays

Style/FrozenStringLiteralComment:
  Enabled: false  # não exige o `# frozen_string_literal: true` no topo

Style/Documentation:
  Enabled: false  # não exige comentários em classes e módulos

Metrics/BlockLength:
  Enabled: false  # não limita o tamanho de métodos com blocos grandes

Metrics/MethodLength:
  Enabled: false  # não limita o tamanho de métodos

  Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

