AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'

# Desativa regras específicas
Style/StringLiterals:
  Enabled: false  # permite usar aspas simples ou duplas

Layout/TrailingWhitespace:
  Enabled: false  # ignora espaços no fim da linha

Layout/TrailingEmptyLines:
  Enabled: false  # ignora linha em branco no fim do arquivo

Layout/LeadingCommentSpace:
  Enabled: false  # ignora falta de espaço após comentários com #

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false  # ignora espaços dentro de colchetes []

Layout/EmptyLinesAroundClassBody:
  Enabled: false  # ignora falta de linhas em branco na classe

Layout/EndAlignment:
  Enabled: false  # ignora desalinhamento de `end`

Style/FrozenStringLiteralComment:
  Enabled: false  # não exige comentário `# frozen_string_literal: true`

Style/Documentation:
  Enabled: false  # não exige comentários em classes e módulos

Metrics/BlockLength:
  Enabled: false  # não limita tamanho de blocos

Metrics/MethodLength:
  Enabled: false  # não limita tamanho de métodos

Rails/ActionFilter:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Rails/HttpStatus:
  Enabled: false

Rails/FilePath:
  Enabled: false

AllCops:
  SuggestExtensions: false
