require:
  - rubocop-rails
  - rubocop-rails-omakase

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Layout/LeadingCommentSpace:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EndAlignment:
  Enabled: false
