# fly.toml app configuration file generated for todo-list-challenge-delicate-forest-6963 on 2025-07-30T13:03:59-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'todo-list-challenge-delicate-forest-6963'
primary_region = 'gru'
console_command = '/rails/bin/rails console'

[build]

[env]
  PORT = '8080'

[processes]
  app = './bin/rails server'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
