default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  username: postgres.oivutgiyzvigkauiwyqx
  password: Edu123!@#
  host: aws-0-sa-east-1.pooler.supabase.com
  database: postgres

test:
  <<: *default
  username: postgres.oivutgiyzvigkauiwyqx
  password: Edu123!@#
  host: aws-0-sa-east-1.pooler.supabase.com
  database: myapp_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  # >>> INÍCIO DAS NOVAS LINHAS PARA A FILA <<<
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %> # Aponta para a mesma URL do DB principal (Supabase)
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %> # Pode ser o mesmo pool de conexões
  # >>> FIM DAS NOVAS LINHAS PARA A FILA <<<