# This file was generated by the `rails generate rspec:install` command.
require 'factory_bot_rails' # ✅ Adicionado para evitar erro de constante não inicializada

RSpec.configure do |config|
  # Configurações do rspec-expectations
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # ✅ Inclui métodos do FactoryBot diretamente nos testes
  config.include FactoryBot::Syntax::Methods

  # Configurações de mocks
  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # Comportamento para contextos compartilhados
  config.shared_context_metadata_behavior = :apply_to_host_groups

  # Ordem aleatória para encontrar dependências ocultas
  config.order = :random
  Kernel.srand config.seed
end
